FROM python:3.12-slim

WORKDIR /app
RUN pip install --no-cache-dir uv
COPY ../microservices/ingestor/pyproject.toml ./
COPY ../microservices/ingestor/src ./src
RUN uv pip install -e .

CMD ["uv", "run", "python", "-m", "ingestor.run_ingest"]
