FROM python:3.12-slim

WORKDIR /app
RUN pip install --no-cache-dir uv

COPY ../microservices/mcp-server/pyproject.toml ./
COPY ../microservices/mcp-server/src ./src
COPY ../microservices/shared/prisma ./prisma

RUN uv pip install -e . \
 && uv run prisma generate --schema=prisma/schema.prisma

CMD ["uv", "run", "python", "src/server.py"]
