import { useState } from 'react';
import { ArrowLeft, CheckCircle2, Clock, Database, FileCode2, FileText, Save, Zap, X, ChevronDown, Brain } from 'lucide-react';
import { SUBMISSIONS, TEMPLATE_GROUPS, TEMPLATES, TEMPLATE_MAP, GROUP_MAP } from '../../data/mockData';

const DIFF_COLOR: Record<string, string> = { Easy: '#2B7A4B', Medium: '#C97C2A', Hard: '#C44B36' };

export function MobileView() {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'code' | 'statement'>('code');
  const [currentTags, setCurrentTags] = useState<string[]>([]);
  const [expandedGroups, setExpandedGroups] = useState<Set<string>>(new Set([TEMPLATE_GROUPS[0].id]));
  const sub = selectedId ? SUBMISSIONS.find(s => s.id === selectedId) : null;
  const toggleGroup = (gid: string) => setExpandedGroups(eg => { const next = new Set(eg); if (next.has(gid)) next.delete(gid); else next.add(gid); return next; });

  if (!sub) return (
    <div className="flex flex-col h-full" style={{ background: '#F3EFE7' }}>
      <div className="flex items-center gap-3 px-4 py-3 shrink-0" style={{ background: '#1B2820', borderBottom: '1px solid rgba(255,255,255,0.07)' }}><Brain size={14} color="#1C8A79" /><span style={{ fontSize: '13px', fontWeight: 600, color: '#F3EFE7', letterSpacing: '0.03em' }}>LeetCode Intelligence</span></div>
      <div className="grid grid-cols-4 mx-4 mt-3 rounded-lg overflow-hidden" style={{ border: '1px solid rgba(27,40,32,0.1)' }}>{[{ label: 'Total', v: SUBMISSIONS.length }, { label: 'AC', v: SUBMISSIONS.filter(s => s.status === 'Accepted').length, c: '#2B7A4B' }, { label: 'Tagged', v: SUBMISSIONS.filter(s => s.tags.length > 0).length, c: '#1C8A79' }, { label: 'Benched', v: SUBMISSIONS.filter(s => s.benchmarkState === 'complete').length, c: '#2D5FC4' }].map(({ label, v, c }: any) => <div key={label} className="flex flex-col items-center py-3" style={{ background: '#F8F6F1' }}><span style={{ fontSize: '18px', fontWeight: 700, color: c ?? '#1B2820', lineHeight: 1 }}>{v}</span><span style={{ fontSize: '9px', color: '#6A7870', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{label}</span></div>)}</div>
      <div className="flex-1 overflow-y-auto mt-3" style={{ scrollbarWidth: 'thin' }}>{SUBMISSIONS.slice(0, 8).map(s => <button key={s.id} onClick={() => { setSelectedId(s.id); setCurrentTags([...s.tags]); }} className="w-full flex items-start gap-3 px-4 py-3 text-left" style={{ borderBottom: '1px solid rgba(27,40,32,0.07)' }}><CheckCircle2 size={14} color="#2B7A4B" style={{ marginTop: 2 }} /><div className="flex-1 min-w-0"><p style={{ fontSize: '13px', fontWeight: 500, color: '#1B2820', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{s.problemTitle}</p><div className="flex items-center gap-2 mt-0.5"><span style={{ fontSize: '11px', color: DIFF_COLOR[s.difficulty] }}>{s.difficulty}</span><span style={{ fontSize: '11px', color: '#6A7870', fontFamily: 'var(--font-mono)' }}>{s.language}</span>{s.tags.length > 0 && <span className="px-1.5 py-0.5 rounded text-[10px]" style={{ background: 'rgba(28,138,121,0.12)', color: '#1C8A79' }}>{s.tags.length} tag{s.tags.length > 1 ? 's' : ''}</span>}</div></div><span style={{ fontSize: '11px', color: '#B5B0A7', marginTop: 2 }}>{s.date.slice(5)}</span></button>)}</div>
      <div className="grid grid-cols-5 shrink-0" style={{ borderTop: '1px solid rgba(27,40,32,0.12)', background: '#F8F6F1' }}>{['Subs','Templates','Graph','Insights','Admin'].map((label, i) => <button key={label} className="flex flex-col items-center py-3 gap-0.5"><div className="w-1.5 h-1.5 rounded-full" style={{ background: i === 0 ? '#1C8A79' : '#B5B0A7' }} /><span style={{ fontSize: '9px', color: i === 0 ? '#1C8A79' : '#B5B0A7', fontWeight: i === 0 ? 600 : 400 }}>{label}</span></button>)}</div>
    </div>
  );

  return (
    <div className="flex flex-col h-full" style={{ background: '#F3EFE7' }}>
      <div className="flex items-center gap-3 px-4 py-3 shrink-0" style={{ background: '#1B2820', borderBottom: '1px solid rgba(255,255,255,0.07)' }}><button onClick={() => setSelectedId(null)}><ArrowLeft size={16} color="rgba(243,239,231,0.6)" /></button><div className="flex-1 min-w-0"><p style={{ fontSize: '13px', fontWeight: 600, color: '#F3EFE7', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{sub.problemTitle}</p><div className="flex items-center gap-2 mt-0.5"><span style={{ fontSize: '10px', color: DIFF_COLOR[sub.difficulty] }}>{sub.difficulty}</span><span style={{ fontSize: '10px', color: 'rgba(243,239,231,0.4)', fontFamily: 'var(--font-mono)' }}>{sub.language}</span></div></div></div>
      <div className="flex items-center gap-2 px-4 py-2 shrink-0 flex-wrap" style={{ borderBottom: '1px solid rgba(27,40,32,0.09)', background: '#F8F6F1' }}><div className="flex items-center gap-1 px-2 py-1 rounded" style={{ background: 'rgba(28,138,121,0.08)', border: '1px solid rgba(28,138,121,0.18)' }}><Clock size={9} color="#1C8A79" /><span style={{ fontSize: '10px', color: '#1C8A79', fontFamily: 'var(--font-mono)' }}>{sub.timeComplexity}</span></div><div className="flex items-center gap-1 px-2 py-1 rounded" style={{ background: 'rgba(45,95,196,0.08)', border: '1px solid rgba(45,95,196,0.18)' }}><Database size={9} color="#2D5FC4" /><span style={{ fontSize: '10px', color: '#2D5FC4', fontFamily: 'var(--font-mono)' }}>{sub.spaceComplexity}</span></div><span style={{ fontSize: '10px', color: '#6A7870' }}>{sub.runtime} · {sub.memory}</span></div>
      <div className="px-4 py-3 shrink-0" style={{ borderBottom: '1px solid rgba(27,40,32,0.09)', background: '#F5F2EB' }}>
        <span style={{ fontSize: '10px', fontWeight: 600, letterSpacing: '0.07em', color: '#6A7870', textTransform: 'uppercase', display: 'block', marginBottom: 8 }}>Template Tags</span>
        <div className="flex flex-wrap gap-1.5 mb-3 min-h-[24px]">{currentTags.length === 0 && <span style={{ fontSize: '11px', color: '#B5B0A7', fontStyle: 'italic' }}>No tags assigned</span>}{currentTags.map(tid => { const t = TEMPLATE_MAP[tid]; const g = t ? GROUP_MAP[t.groupId] : null; return <span key={tid} className="flex items-center gap-1 px-2 py-0.5 rounded" style={{ background: (g?.color ?? '#1C8A79') + '18', border: `1px solid ${(g?.color ?? '#1C8A79')}40`, color: g?.color ?? '#1C8A79', fontSize: '11px', fontWeight: 500 }}>{t?.name}<X size={9} onClick={() => setCurrentTags(ct => ct.filter(x => x !== tid))} style={{ cursor: 'pointer', opacity: 0.7 }} /></span>; })}</div>
        {TEMPLATE_GROUPS.map(group => { const expanded = expandedGroups.has(group.id); const groupTemplates = TEMPLATES.filter(t => t.groupId === group.id); return <div key={group.id} className="mb-1.5 rounded overflow-hidden" style={{ border: `1px solid ${group.color}25` }}><button onClick={() => toggleGroup(group.id)} className="w-full flex items-center justify-between px-3 py-2" style={{ background: group.color + '08' }}><div className="flex items-center gap-2"><div className="w-2 h-2 rounded-full" style={{ background: group.color }} /><span style={{ fontSize: '11px', fontWeight: 600, color: group.color }}>{group.name}</span></div><ChevronDown size={11} color={group.color} style={{ transform: expanded ? 'rotate(0deg)' : 'rotate(-90deg)' }} /></button>{expanded && <div className="flex flex-wrap gap-1.5 p-2">{groupTemplates.map(t => { const tagged = currentTags.includes(t.id); return <button key={t.id} onClick={() => { if (tagged) setCurrentTags(ct => ct.filter(x => x !== t.id)); else setCurrentTags(ct => [...ct, t.id]); }} className="px-2 py-0.5 rounded transition-all" style={{ background: tagged ? group.color + '20' : 'rgba(27,40,32,0.05)', border: `1px solid ${tagged ? group.color + '50' : 'rgba(27,40,32,0.1)'}`, color: tagged ? group.color : '#6A7870', fontSize: '11px', fontWeight: tagged ? 500 : 400 }}>{tagged && '✓ '}{t.name}</button>; })}</div>}</div>; })}
      </div>
      <div className="flex shrink-0" style={{ borderBottom: '1px solid rgba(27,40,32,0.1)', background: '#F8F6F1' }}>{[{ key: 'code', label: 'Code', icon: FileCode2 }, { key: 'statement', label: 'Problem', icon: FileText }].map(({ key, label, icon: Icon }) => <button key={key} onClick={() => setActiveTab(key as any)} className="flex items-center gap-1.5 px-4 py-2.5" style={{ borderBottom: activeTab === key ? '2px solid #1C8A79' : '2px solid transparent', fontSize: '11px', fontWeight: activeTab === key ? 600 : 400, color: activeTab === key ? '#1C8A79' : '#6A7870', marginBottom: -1, cursor: 'pointer' }}><Icon size={11} />{label}</button>)}</div>
      <div className="flex-1 overflow-auto" style={{ scrollbarWidth: 'thin' }}>{activeTab === 'code' ? <pre className="p-4" style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', color: '#C8D8D4', lineHeight: 1.7, background: '#1B2820', margin: 0, minHeight: '100%' }}>{sub.code}</pre> : <pre className="p-4" style={{ fontFamily: 'var(--font-sans)', fontSize: '12px', color: '#3A4840', lineHeight: 1.8, whiteSpace: 'pre-wrap', margin: 0 }}>{sub.problemStatement}</pre>}</div>
      <div className="flex items-center gap-2 px-4 py-3 shrink-0" style={{ borderTop: '1px solid rgba(27,40,32,0.1)', background: '#F0ECE4' }}><button className="flex-1 flex items-center justify-center gap-1.5 py-2 rounded" style={{ background: '#1B2820', color: '#F3EFE7', fontSize: '12px', fontWeight: 500, border: '1px solid rgba(27,40,32,0.8)' }}><Save size={12} />Save</button><button className="flex-1 flex items-center justify-center gap-1.5 py-2 rounded" style={{ background: 'rgba(45,95,196,0.12)', color: '#2D5FC4', fontSize: '12px', fontWeight: 500, border: '1px solid rgba(45,95,196,0.3)' }}><Zap size={12} />Benchmark</button></div>
      <div className="grid grid-cols-5 shrink-0" style={{ borderTop: '1px solid rgba(27,40,32,0.12)', background: '#F8F6F1' }}>{['Subs','Templ','Graph','Insights','Admin'].map((label, i) => <button key={label} className="flex flex-col items-center py-2.5 gap-0.5"><div className="w-1.5 h-1.5 rounded-full" style={{ background: i === 0 ? '#1C8A79' : '#B5B0A7' }} /><span style={{ fontSize: '9px', color: i === 0 ? '#1C8A79' : '#B5B0A7', fontWeight: i === 0 ? 600 : 400 }}>{label}</span></button>)}</div>
    </div>
  );
}
