import type { PatternTagOption, SubmissionRow, TemplateBenchmarkResult } from './data';

function makeTemplateBenchmark(): TemplateBenchmarkResult {
  return {
    submissionId: 'sub-1',
    model: 'openai/gpt-4.1-mini',
    excludedGroupKeys: [],
    scores: [
      {
        key: 'graph-bfs-dfs',
        patternTagId: 'tag-template-graph-bfs',
        score: 85,
        confidence: 71,
        reason: 'BFS over a grid is a graph traversal pattern with shortest-path semantics.',
        evidence: ['Uses BFS traversal', 'Tracks visited nodes', 'Explores neighbors level-by-level'],
      },
      {
        key: 'grid-bfs-unweighted-shortest-path',
        patternTagId: 'tag-template-grid-bfs',
        score: 100,
        confidence: 91,
        reason: 'This is the canonical unweighted shortest path template on a grid.',
        evidence: ['Frontier expands by distance', 'Grid states become graph nodes'],
      },
    ],
  };
}

export function makeTagWorkbenchTags(): PatternTagOption[] {
  return [
    {
      id: 'tag-template-linear-hash',
      key: 'hash-map-lookup',
      label: 'Hash map lookup',
      dimension: 'template',
      kind: 'tag',
      source: 'seeded',
      assignmentCount: 20,
      description: 'Lookup or count values with a hash map.',
      metadata: {
        whenToUse: ['Need O(1) average lookups'],
        signals: ['counting', 'membership'],
        invariants: ['Map stores the current state'],
        pseudocode: ['for item in items', ' update map'],
        classicProblems: ['Two Sum'],
        relatedDataStructures: ['Hash map'],
        similarTemplates: [],
        whenNotToUse: [],
        defaultComplexity: { time: 'O(n)', space: 'O(n)' },
      },
      parentId: 'group-linear',
      parentKey: 'linear_state_hashing',
      parentLabel: 'Linear state and hashing',
      sortOrder: 1,
    },
    {
      id: 'tag-template-graph-bfs',
      key: 'graph-bfs-dfs',
      label: 'Graph BFS/DFS',
      dimension: 'template',
      kind: 'tag',
      source: 'seeded',
      assignmentCount: 85,
      description: 'Explore graph or grid states while tracking visited nodes.',
      metadata: {
        classicProblems: ['Number of Islands', 'Shortest Path in Binary Matrix'],
        whenToUse: ['Need connected components, reachability, or shortest unweighted expansions.'],
        whenNotToUse: ['Dependencies form a DAG and require ordering.', 'Need dynamic connectivity under unions.'],
        signals: ['graph', 'grid', 'visited', 'component'],
        pseudocode: ['frontier = [start]', 'visited = {start}', 'while frontier:', ' node = pop frontier'],
        invariants: ['Visited nodes are never processed twice.', 'Frontier contains discovered but unresolved nodes.'],
        defaultComplexity: { time: 'O(m * n)', space: 'O(m + n)' },
        relatedDataStructures: ['Queue / Deque', 'Graph'],
        similarTemplates: ['grid-bfs-unweighted-shortest-path'],
      },
      parentId: 'group-structures',
      parentKey: 'structures_and_traversal',
      parentLabel: 'Structures and traversal',
      sortOrder: 2,
    },
    {
      id: 'tag-template-grid-bfs',
      key: 'grid-bfs-unweighted-shortest-path',
      label: 'Grid BFS for unweighted shortest path',
      dimension: 'template',
      kind: 'tag',
      source: 'llm_generated',
      assignmentCount: 5,
      description: 'Specialized BFS for shortest paths on a grid with uniform edge weights.',
      metadata: {
        classicProblems: ['Shortest Path in Binary Matrix'],
        whenToUse: ['The board is a grid and every move has uniform cost.'],
        whenNotToUse: ['Weighted edges require Dijkstra.'],
        signals: ['grid', 'shortest path', 'uniform cost'],
        pseudocode: ['queue = deque([(start, 0)])', 'for neighbor in directions:'],
        invariants: ['Each cell enters the queue at most once.'],
        defaultComplexity: { time: 'O(m * n)', space: 'O(m * n)' },
        relatedDataStructures: ['Queue / Deque', 'Grid / Matrix'],
        similarTemplates: ['graph-bfs-dfs'],
      },
      parentId: 'group-structures',
      parentKey: 'structures_and_traversal',
      parentLabel: 'Structures and traversal',
      sortOrder: 3,
    },
    {
      id: 'tag-template-backtracking',
      key: 'backtracking',
      label: 'Backtracking',
      dimension: 'template',
      kind: 'tag',
      source: 'seeded',
      assignmentCount: 5,
      description: 'Recursive search with choose-explore-unchoose.',
      metadata: {
        classicProblems: ['Subsets'],
        whenToUse: ['Need exhaustive search over combinations.'],
        whenNotToUse: ['State space is too large without pruning.'],
        signals: ['subset', 'permutation'],
        pseudocode: ['choose', 'explore', 'unchoose'],
        invariants: ['State resets after each branch.'],
        defaultComplexity: { time: 'O(2^n)', space: 'O(n)' },
        relatedDataStructures: ['Array'],
        similarTemplates: [],
      },
      parentId: 'group-recursion',
      parentKey: 'recursion_optimization_design',
      parentLabel: 'Recursion, optimization, and design',
      sortOrder: 4,
    },
    {
      id: 'tag-ds-grid',
      key: 'ds-grid',
      label: 'Grid / Matrix',
      dimension: 'data_structure',
      kind: 'tag',
      source: 'seeded',
      assignmentCount: 22,
      description: 'Problems modeled on a 2D board.',
      metadata: null,
      parentId: 'group-ds',
      parentKey: 'data_structure',
      parentLabel: 'data structure',
      sortOrder: 5,
    },
    {
      id: 'tag-ds-queue',
      key: 'ds-queue',
      label: 'Queue / Deque',
      dimension: 'data_structure',
      kind: 'tag',
      source: 'seeded',
      assignmentCount: 14,
      description: 'FIFO exploration or deque-based transitions.',
      metadata: null,
      parentId: 'group-ds',
      parentKey: 'data_structure',
      parentLabel: 'data structure',
      sortOrder: 6,
    },
  ];
}

export function makeTagWorkbenchSubmissions(): SubmissionRow[] {
  return [
    {
      id: 'sub-1',
      titleSlug: 'shortest-path-in-binary-matrix',
      title: 'Shortest Path in Binary Matrix',
      difficulty: 'Medium',
      relatedProblems: ['1091'],
      status: 'Accepted',
      createdAt: '2026-06-22T18:27:00.000Z',
      templateBenchmarkOptOut: false,
      language: 'python3',
      timeComplexity: 'O(m * n)',
      spaceComplexity: 'O(m + n)',
      thought: 'Level-order BFS guarantees the first time we reach the target is the shortest path.',
      questionDescription: 'Given an n x n binary matrix grid, return the length of the shortest clear path.',
      submissionCode: [
        'from collections import deque',
        '',
        'def shortestPathBinaryMatrix(grid):',
        '    queue = deque([(0, 0, 1)])',
        '    seen = {(0, 0)}',
        '    return 1',
      ].join('\n'),
      templateBenchmark: makeTemplateBenchmark(),
      tags: [
        {
          id: 'tag-template-graph-bfs',
          key: 'graph-bfs-dfs',
          label: 'Graph BFS/DFS',
          dimension: 'template',
          kind: 'tag',
          parentId: 'group-structures',
          parentKey: 'structures_and_traversal',
          parentLabel: 'Structures and traversal',
        },
        {
          id: 'tag-template-grid-bfs',
          key: 'grid-bfs-unweighted-shortest-path',
          label: 'Grid BFS for unweighted shortest path',
          dimension: 'template',
          kind: 'tag',
          parentId: 'group-structures',
          parentKey: 'structures_and_traversal',
          parentLabel: 'Structures and traversal',
        },
        {
          id: 'tag-ds-grid',
          key: 'ds-grid',
          label: 'Grid / Matrix',
          dimension: 'data_structure',
          kind: 'tag',
          parentId: 'group-ds',
          parentKey: 'data_structure',
          parentLabel: 'data structure',
        },
        {
          id: 'tag-ds-queue',
          key: 'ds-queue',
          label: 'Queue / Deque',
          dimension: 'data_structure',
          kind: 'tag',
          parentId: 'group-ds',
          parentKey: 'data_structure',
          parentLabel: 'data structure',
        },
      ],
    },
    {
      id: 'sub-2',
      titleSlug: 'shortest-path-in-binary-matrix',
      title: 'Shortest Path in Binary Matrix',
      difficulty: 'Medium',
      relatedProblems: ['1091'],
      status: 'Accepted',
      createdAt: '2026-06-22T17:06:00.000Z',
      templateBenchmarkOptOut: true,
      language: 'python3',
      timeComplexity: 'O(m * n)',
      spaceComplexity: 'O(m + n)',
      thought: null,
      questionDescription: null,
      submissionCode: 'def shortestPathBinaryMatrix(grid):\n    return -1',
      templateBenchmark: null,
      tags: [],
    },
    {
      id: 'sub-3',
      titleSlug: 'open-the-lock',
      title: 'Open the Lock',
      difficulty: 'Medium',
      relatedProblems: ['752'],
      status: 'Accepted',
      createdAt: '2026-06-21T14:00:00.000Z',
      templateBenchmarkOptOut: false,
      language: 'python3',
      timeComplexity: 'O(10^4)',
      spaceComplexity: 'O(10^4)',
      thought: null,
      questionDescription: 'Open the lock with minimum turns.',
      submissionCode: 'def openLock(deadends, target):\n    return 6',
      templateBenchmark: null,
      tags: [],
    },
  ];
}
